db.Restaurants.find()
db.Restaurants.find({}, {restaurant_id: 1, name:1, borough:1, cuisine:1})
db.Restaurants.find({}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine:1})
db.Restaurants.find({}, {,restaurant_id: 1, name:1, borough:1, "address.zipcode":1})
db.Restaurants.find({borough:"Bronx"}, {_id:0,restaurant_id: 1, name:1})
db.Restaurants.find({borough:"Bronx"}, {_id:0,restaurant_id: 1, name:1}).limit(5)
db.Restaurants.find({borough:"Bronx"}, {_id:0,restaurant_id: 1, name:1}).skip(5).limit(5)
db.Restaurants.find({"grades.score": {$gt: 90}}, {_id:0,restaurant_id: 1, name:1})
db.Restaurants.find({"grades.score": {$gt: 80, $lt: 100}}, {_id:0,restaurant_id: 1, name:1})
db.Restaurants.find({"address.coord.0": {$lt: -95.754168}}, {_id:0,restaurant_id: 1, name:1})
db.Restaurants.find({$and: [{cuisine: {$ne: "American"}, "grades.score": {$gt: 70}, "address.coord.0": {$lt: -65.754168}}]}, {_id:0,restaurant_id: 1, name:1})
db.Restaurants.find({cuisine: {$ne: "American"}, "grades.score": {$gt: 70}, "address.coord.0": {$lt: -65.754168}}, {_id:0,restaurant_id: 1, name:1})
db.Restaurants.find({cuisine: {$ne: "American"}, "grades.grade": "A", borough: {$ne: "Brooklyn"}}, {_id:0,restaurant_id: 1, name:1, cuisine: 1}).sort( {cuisine: -1})
db.Restaurants.find({name: {$regex: "^Wil"}}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine: 1})
db.Restaurants.find({name: {$regex: "ces$"}}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine: 1})
db.Restaurants.find({name: {$regex: "(?)Reg(?)"}}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine: 1})
db.Restaurants.find({borough: "Bronx", cuisine: { $in: ["American ",  "Chinese"]}}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine: 1})
db.Restaurants.find({borough: { $in: ["Bronx","Brooklyn", "Queens", "Staten Island"]}}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine: 1})
db.Restaurants.find({borough: { $nin: ["Bronx","Brooklyn", "Queens, Staten Island"]}}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine: 1})
db.Restaurants.find({"grades.score": {$lte: 10}}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine: 1, "grades.score":1})
db.Restaurants.find({$or: [{name: {$regex: "Wil"}, cuisine: {$nin: ["American ", "Chinese"]}}]}, {_id:0,restaurant_id: 1, name:1, borough:1, cuisine: 1, "grades.score":1})
db.Restaurants.find({grades: { date: ISODate("2014-08-11T00:00:00.000Z"), grade: 'A', score: 11 }}, {_id:0,restaurant_id: 1, name:1, grades: 1})
db.Restaurants.find({"grades.1": { date: ISODate("2014-08-11T00:00:00.000Z"), grade: 'A', score: 9 }}, {_id:0,restaurant_id: 1, name:1, grades: 1})
db.Restaurants.find({"address.coord.1": {$gt: 42, $lte: 52}}, {_id:0,restaurant_id: 1, name:1, address: 1, })
db.Restaurants.find({}, {_id:0, restaurant_id: 1, name:1}).sort({name:1})
db.Restaurants.find({}, {_id:0, restaurant_id: 1, name:1}).sort({name: -1})
db.Restaurants.find({}, {_id:0, restaurant_id: 1, name:1, cuisine: 1, borough: 1}).sort({cuisine: 1, borough: -1})
db.Restaurants.find({"address.street": null}, {_id:0, restaurant_id: 1, name:1, cuisine: 1, borough: 1})
db.Restaurants.find({"address.coord": {$type: "double"}}, {_id:0, restaurant_id: 1, name:1, cuisine: 1, borough: 1})
db.Restaurants.find({"grades.score": {$mod: [7,0]}}, {_id:0,restaurant_id: 1, name:1, grades: 1})
db.Restaurants.find({name: {$regex: "(?)mon(?)"}}, {name:1, borough: 1, "address.coord": 1, cuisine: 1})
db.Restaurants.find({name: {$regex: "^Mad"}}, {name:1, borough: 1, "address.coord": 1, cuisine: 1})